### ISSUE TITLE
video 

### ISSUE THREAD

**Issue by addonme** [DefinetlyNotAI/Solidworks-Crack#1]
ı dont see video can you help me ?

**Comment by DefinetlyNotAI** [comment]
Hi @addonme You have to download the video, GitHub cant inherently play videos, so what you have to do is the following, I appologize if its complicated:

Click on the green code button, select download as ZIP file, it will download the instructions and video as a zip file,

Open the zip file, and take all contents and put them in your desktop, then double click the video and enjoy


Please leave a Star on my repository, thank you :)

**Comment by DefinetlyNotAI** [comment]
Hello, from one pirate to another, I must ask,
Do you still have the ZIP file from the guide link? It seems `GetIntoPC` is down, and many other people can't use Solidworks Cracked

If you do, sacrifice some of your time and upload it to google drive, and allow me to download it, so I may host it locally HERE!

---

Thank you 🫡
