### ISSUE TITLE
Error While installing solidworks

### ISSUE THREAD

**Issue by R2025Git** [DefinetlyNotAI/Solidworks-Crack#10]
After doing alll steps properly i still getting error while installing. I have attached screenshot and log, hope u can help
![Screenshot 2024-10-09 221632](https://github.com/user-attachments/assets/a50fed4b-a4ab-4d70-ba4d-fcaeb836703f)
[SummaryIMLog_20240-40301-1100_00001.txt](https://github.com/user-attachments/files/17322091/SummaryIMLog_20240-40301-1100_00001.txt)
[SummaryIMLog_20240-40301-1100_00002.txt](https://github.com/user-attachments/files/17322093/SummaryIMLog_20240-40301-1100_00002.txt)
[SummaryIMLog_20240-40301-1100_00003.txt](https://github.com/user-attachments/files/17322094/SummaryIMLog_20240-40301-1100_00003.txt)
[SummaryIMLog_20240-40301-1100_00004.txt](https://github.com/user-attachments/files/17322095/SummaryIMLog_20240-40301-1100_00004.txt)
[Other Logs.zip](https://github.com/user-attachments/files/17322099/Other.Logs.zip)

**Comment by DefinetlyNotAI** [comment]
Which tutorial did you follow

**Comment by R2025Git** [comment]
> Which tutorial did you follow

The one which you linked

**Comment by DefinetlyNotAI** [comment]
Can you attempt uninstalling and using my video tutorial?
That tutorial is not mine - so i cant verify anything

**Comment by R2025Git** [comment]
> Can you attempt uninstalling and using my video tutorial? That tutorial is not mine - so i cant verify anything

Can send the link for the yt video?

**Comment by DefinetlyNotAI** [comment]
Yo, the vid must be downloaded, as yt strikes pirating vids - [download](https://github.com/DefinetlyNotAI/Solidworks-Crack/raw/refs/heads/main/SolidWorks_2021_Tutorial.mp4)

Sorry for the inconveniance - this is for 2021 - but should work with 2024

**Comment by R2025Git** [comment]
Ran into a new issue now. Any fix?

![Screenshot 2024-10-11 161042](https://github.com/user-attachments/assets/d6d0630c-f936-4b01-b9a1-4a812580e539)
[sldIMLog_20240-40100-1100_00001.txt](https://github.com/user-attachments/files/17341501/sldIMLog_20240-40100-1100_00001.txt)
![Screenshot 2024-10-11 161400](https://github.com/user-attachments/assets/d7f2831a-ac6d-42c8-ada8-97c5e84fa1f2)

**Comment by DefinetlyNotAI** [comment]
Hmm, First go to these locations and fully delete them:
Install IoBit uninstaller to safely delete everything solidwork related
Delete Solidworks with the uninstaller
Check these paths if the file is still there
Check your C:/ and StartMenu for any solidwork file
Restart your device, and restart installation - selecting the first option from the image

As advice, delete the installation you did, and attempt to undo them
```
C:\Program Files\SOLIDWORKS Corp\eDrawings  
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS CAM
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Composer
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Electrical
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Explorer
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Flow Simulation
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Inspection
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Manage Client
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS PCB
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS PDM
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Plastics
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Visualize
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Visualize Boost
```

**Comment by LasTCK** [comment]
Do you have any plans for the 2025 program?

**Comment by R2025Git** [comment]
I reset the windows and managed to install all except Solidworks Electrical, but still getting issues with SQL server installation, but I don't need Solidworks Electrical, so it doesn't matter, My issue was fixed I guess you can close the post, Thanks for your HELP 😊

**Comment by DefinetlyNotAI** [comment]
No problem - Can you atleast drop a star? I would greatly appreciate it if you also drop a follow

**Comment by DefinetlyNotAI** [comment]
> Do you have any plans for the 2025 program?

Most likely - yes, but only if the feedback of this was positive - if I see that its too much of a hassle to continue - I will most likely archive this. Hope i answered you question @LasTCK

**Comment by R2025Git** [comment]
> No problem - Can you atleast drop a star? I would greatly appreciate it if you also drop a follow

Done 👍

**Comment by DefinetlyNotAI** [comment]
> > No problem - Can you atleast drop a star? I would greatly appreciate it if you also drop a follow
> 
> Done 👍

Thank you very much ⭐
