### ISSUE TITLE
Getting the license error issue (-8 554 0) but on the 2021 version somehow

### ISSUE THREAD

**Issue by Nineh-h** [DefinetlyNotAI/Solidworks-Crack#13]
### Prerequisites

- [X] I have [searched](https://github.com/DefinetlyNotAI/Solidworks-Crack/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues.
- [ ] I have made sure the issue is not related to (-8 554 0).

### Describe the issue

Title explains it. I know one of the prerequisites is not mentioning the issue, but it was said to only happen with the 2024 version. I did it with the 2021 but the problem is still there.

### Which tutorial did you follow

README Guide

### Any error codes from Solidworks?

(-8 554 0)

**Comment by DefinetlyNotAI** [comment]
Hmm, now that is a surprise?

Can you send me some screenshots, as well as give me any info of your device - maybe which windows build?

May you please run this command on your device (PowerShell or CMD) and reply with the output in a code block, More on how to do this here [here](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks), GitHub uses backticks

Command: `systeminfo` - feel free to check what the command actually does - Remember never trust anyone from the internet😉

Finally - May you drop a star or a follow, I would really appreciate it,

**Comment by Nineh-h** [comment]
Screenshots:
![Screenshot 2024-10-14 232355](https://github.com/user-attachments/assets/e74dee12-8adc-4257-84d7-908b19dfd8c4)

Additional information:
Windows 11 home edition
OS Version 10.0.22631 N/A Build 22631
Asus PC
x64 OS
16 GB Ram
12th gen i7 processor
RTX 3060

**Comment by DefinetlyNotAI** [comment]
Hmm - this is very weird, i can't seem to know the problem itself - can you please try re-installing and uninstalling again?

Sorry, this error does happen, but the crack software doesn't originate from me

**Comment by Nineh-h** [comment]
Is there a way to fully uninstall the program in such a way that there's no leftover processes?

**Comment by DefinetlyNotAI** [comment]
Yes,
Install IoBit uninstaller to safely delete everything Solidworks related (Search Solidworks in the search bar)
Delete Solidworks with the uninstaller - Check the option to delete residual files - Here is a free key for the pro edition (As a sorry) - `DBD63-84819-C934D-208TC` Its a giveaway key.
Check your C:/ and StartMenu directory for any Solidworks file or folder

Then check these paths, and delete them fully if they exist:
```
C:\Program Files\SOLIDWORKS Corp\eDrawings  
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS CAM
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Composer
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Electrical
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Explorer
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Flow Simulation
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Inspection
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Manage Client
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS PCB
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS PDM
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Plastics
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Visualize
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Visualize Boost
```

---

you may re-attempt to download it again, as it may be a one-time bug

Sorry for the inconveniance

Then it may be possible after a restart

**Comment by Nineh-h** [comment]
So I uninstalled everything and am attempting the reinstall. However, this time I now realize I had a weird message when trying to install the first time too. 
![Screenshot 2024-10-16 201753](https://github.com/user-attachments/assets/160d5fbf-6211-498d-ac2a-42becc5bed0f)
No matter how many times I reboot the message doesn't change.

**Comment by DefinetlyNotAI** [comment]
If you have rebooted - Press ok - this message is just cause it couldn't find all other files, thanks to the full delete

**Comment by Nineh-h** [comment]
Even after a reinstall it still presents the same issue

**Comment by DefinetlyNotAI** [comment]
Same error code?

**Comment by Nineh-h** [comment]
yeah, unfortunately

**Comment by DefinetlyNotAI** [comment]
Hmm, try 2024 version - I am honestly surprised this happened, and so I have no idea why - so sorry, but can you please try 2024 version?

Sorry again,
