### ISSUE TITLE
While opening Solidworks visualise there is a licence error.

### ISSUE THREAD

**Issue by Qbert222** [DefinetlyNotAI/Solidworks-Crack#15]
### Prerequisites

- [X] I have [searched](https://github.com/DefinetlyNotAI/Solidworks-Crack/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues.
- [X] I have made sure the issue is not related to (-8 554 0).

### Describe the issue

Solidworks has been installed and is working perfectly fine. But when opening Solidworks visialize it's showing a licence error. Do you know how to fix it.

### Which tutorial did you follow

None

**Comment by DefinetlyNotAI** [comment]
Sorry, But I cannot help you with anything OUTSIDE my guide's

I am not sure what or how you installed your Solidworks - but I cant help, I am sorry

---

Though if you re-install Solidworks, it should work again

**Comment by Qbert222** [comment]
I installed it with your guide. It's 2024 version

**Comment by Qbert222** [comment]
I reinstalled it but visualise is not working

**Comment by DefinetlyNotAI** [comment]
which guide? The updated or readme or video??

**Comment by edatronique** [comment]
Same problem with the updated guide

**Comment by DefinetlyNotAI** [comment]
@edatronique Open a new issue please

**Comment by DefinetlyNotAI** [comment]
Closed as stale
