### ISSUE TITLE
solid works will not open, closes and makes crash report

### ISSUE THREAD

**Issue by spezzmachining** [DefinetlyNotAI/Solidworks-Crack#17]
### Prerequisites

- [X] I have [searched](https://github.com/DefinetlyNotAI/Solidworks-Crack/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues.
- [X] I have made sure the issue is not related to (-8 554 0).

### Describe the issue

when opening, give message about user defined tabs, pressing either yes or no create
![Screenshot 2024-11-25 issue 1](https://github.com/user-attachments/assets/92a95b0c-5bb6-4b31-909f-e4f9e95fe49a)
![Screenshot 2024-11-25 130940](https://github.com/user-attachments/assets/b2d18126-e2d1-4329-a9d8-a3a3ec382275)
s crash report

### Which tutorial did you follow

Attached video

### Any error codes from Solidworks?

no

**Comment by DefinetlyNotAI** [comment]
Hi, attempt to run the fix it asks for and restart solidworks, - also to attach the error report (click preview)

This is so I can help you better, thanks

---

Finally - May you drop a star or a follow, I would really appreciate it,

**Comment by DefinetlyNotAI** [comment]
Hello, Attachement is not seen, can you go here, https://github.com/DefinetlyNotAI/Solidworks-Crack/issues/17 and attach it?

**Comment by spezzmachining** [comment]
> ### Prerequisites
> * [x]  I have [searched](https://github.com/DefinetlyNotAI/Solidworks-Crack/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues.
> * [x]  I have made sure the issue is not related to (-8 554 0).
> 
> ### Describe the issue
> when opening, give message about user defined tabs, pressing either yes or no create ![Screenshot 2024-11-25 issue 1](https://private-user-images.githubusercontent.com/189655953/389650791-92a95b0c-5bb6-4b31-909f-e4f9e95fe49a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MzUyODksIm5iZiI6MTczMjYzNDk4OSwicGF0aCI6Ii8xODk2NTU5NTMvMzg5NjUwNzkxLTkyYTk1YjBjLTViYjYtNGIzMS05MDlmLWU0ZjllOTVmZTQ5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxNTI5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWM2MGZiZmMyZDFiOTk4NGEyZmIxMTcyNzA2NWFlNmQzMzhlOTVmYTkzY2FjZTZhNTk1MmM2MjBmZTQ2Yjc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QRk8Hb_jzSRLXKhcm8zICJPfVWOOPPqeitq-Ok9auo8) ![Screenshot 2024-11-25 130940](https://private-user-images.githubusercontent.com/189655953/389650859-b2d18126-e2d1-4329-a9d8-a3a3ec382275.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MzUyODksIm5iZiI6MTczMjYzNDk4OSwicGF0aCI6Ii8xODk2NTU5NTMvMzg5NjUwODU5LWIyZDE4MTI2LWUyZDEtNDMyOS1hOWQ4LWEzYTNlYzM4MjI3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxNTI5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzg0MTYwNjY4ZjQ1YTc2MzBiY2MzYjEzYjAxZWNiNmI0YzZhZDk4ZmFjYmRmODA5NmMzMmVmMTM3NjFiNzYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MdlxdmjH8vuhKpuufftvQgMSCp71aNkBFwq9NL2Qmh8) s crash report
> 
> ### Anything else?
> _No response_
> 
> ### Which tutorial did you follow
> Attached video
> 
> ### Any error codes from Solidworks?
> no

[

[SolidWorksPerformance.log](https://github.com/user-attachments/files/17921861/SolidWorksPerformance.log)

**Comment by DefinetlyNotAI** [comment]
Error Diagnostics:

Unhandled exception (C++ Exception), with a potential error in menu modification routines (suAppCustomizationMgr_c).
Stack trace and memory usage info.

---

First uninstall your solidworks, then install a new updated version of C++, then reinstall solidworks from the video, the error seems to be from CPP

**Comment by spezzmachining** [comment]
Ok, I will try that, thanks


Sent from the all new AOL app for iOS


On Tuesday, November 26, 2024, 12:28 PM, Shahm Najeeb ***@***.***> wrote:




Error Diagnostics:

Unhandled exception (C++ Exception), with a potential error in menu modification routines (suAppCustomizationMgr_c).
Stack trace and memory usage info.

First uninstall your solidworks, then install a new updated version of C++, then reinstall solidworks from the video, the error seems to be from CPP

**Comment by spezzmachining** [comment]
I believe i have the newest version of C++ or is it the visual studio tools that need updating?see attached
    On Tuesday, November 26, 2024 at 12:28:57 p.m. EST, Shahm Najeeb ***@***.***> wrote:   

 


Error Diagnostics:

Unhandled exception (C++ Exception), with a potential error in menu modification routines (suAppCustomizationMgr_c).
Stack trace and memory usage info.

First uninstall your solidworks, then install a new updated version of C++, then reinstall solidworks from the video, the error seems to be from CPP

**Comment by DefinetlyNotAI** [comment]
Most likely the VS tools, This exception seems to be from solidworks itself, and not the fact its cracked, So i will attempt to help, but most likely a clean install would be the best
