### ISSUE TITLE
(2021 ver.) Error. Newer version is already installed. But I have no other SW installed

### ISSUE THREAD

**Issue by Michalloyd** [DefinetlyNotAI/Solidworks-Crack#18]
### Prerequisites

- [X] I have [searched](https://github.com/DefinetlyNotAI/Solidworks-Crack/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues.
- [X] I have made sure the issue is not related to (-8 554 0).

### Describe the issue

![stupid solid](https://github.com/user-attachments/assets/3d6167f2-e604-4bdd-a963-59274cd9656f)
![more stupid solid](https://github.com/user-attachments/assets/79569361-0d58-4f3f-ab8b-ed3ff3f20fad)
![screw solid](https://github.com/user-attachments/assets/80694be6-f7e3-448b-aafd-99400b62ecb3)
I have been running into this issue and I have no idea how to solve it. I did have Solidworks installed before but I uninstalled it with Revo Uninstaller so it should be properly uninstalled. 

I should also add that I tried searching for the VBA 7.1 file but unsuccessfully.

**Comment by DefinetlyNotAI** [comment]
Question, is this from my cracked guide, or is it related to you?

Now follow these instructions to fully uninstall Solidworks:
- Make a system recovery point ( In case you mess something up, you can rollback safely )
- Install IoBit uninstaller and safely delete everything Solidworks related, including residual files and registry, you can get a pro key for free if you search in the internet these may work:
    - License code 1: 5FE5E-27FD1-9217B-389TD
    - License code 2: 3D7CB-22411-E78C5-DCCBD (License Exp. Date: Apr 24, 2025)
- Check paths below and remove them if they still exist
- Check your `C:/` and `StartMenu` for any Solidworks file's still there
- Restart your device, and restart the installation

Paths to check:
```
C:\Program Files\SOLIDWORKS Corp\eDrawings  
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS CAM
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Composer
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Electrical
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Explorer
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Flow Simulation
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Inspection
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Manage Client
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS PCB
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS PDM
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Plastics
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Visualize
C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS Visualize Boost
```

Finally - May you drop a star or a follow, I would really appreciate it,

**Comment by DefinetlyNotAI** [comment]
If all of these don't work, send me the logs of Solidworks

**Comment by DefinetlyNotAI** [comment]
This issue is Stale, to reopen the issue, just ask us to do so, thanks
