### ISSUE TITLE
Install Multiple Versions of SOLIDWORKS on One Computer

### ISSUE THREAD

**Issue by PhongTong** [DefinetlyNotAI/Solidworks-Crack#19]
### Prerequisites

- [X] I have [searched](https://github.com/DefinetlyNotAI/Solidworks-Crack/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues.
- [X] I have made sure the issue is not related to (-8 554 0).

### Describe the issue

Can I have more than one version of SOLIDWORKS cracked on my system at the same time? Right now I use SW2019 version and want to install newer version for new file version

### Which tutorial did you follow

None

**Comment by DefinetlyNotAI** [comment]
Yo, you can try lol, I haven't tried, but based on other people who followed the guides, they said Yes, but do note it may be tricky, make sure NO files clash with each other,

---

Sorry for the late response, was in the midst of changing homes
