### ISSUE TITLE
license

### ISSUE THREAD

**Issue by Tudor46** [DefinetlyNotAI/Solidworks-Crack#2]
So if I don't have an excel license it wont work?

**Comment by DefinetlyNotAI** [comment]
No, Solidworks as a software is dependant on excel, even the original version, you can however crack the excel software then use my guide, please drop me a star on my repo, thx

**Comment by Tudor46** [comment]
I will ,thanks!

**Comment by DefinetlyNotAI** [comment]
And may you drop me a follow :)

**Comment by DefinetlyNotAI** [comment]
Hello, from one pirate to another, I must ask,
Do you still have the ZIP file from the guide link? It seems `GetIntoPC` is down, and many other people can't use Solidworks Cracked

If you do, sacrifice some of your time and upload it to google drive, and allow me to download it, so I may host it locally HERE!

---

Thank you 🫡
