### ISSUE TITLE
Solidworks license error - Could not obtain a license for Solidworks standard (-8 544 0)

### ISSUE THREAD

**Issue by naughty360** [DefinetlyNotAI/Solidworks-Crack#3]
the extra files downloaded the SolidWorks standard version and i keep getting licence error when i try to open the app to do my design

**Comment by DefinetlyNotAI** [comment]
Can you @naughty360 show me some images? Or any specific details so I can help you, like what step did it fail, or did you use the video or text guide?

**Comment by naughty360** [comment]
> Can you @naughty360 show me some images? Or any specific details so I can help you, like what step did it fail, or did you use the video or text guide?

![Screenshot (116)](https://github.com/user-attachments/assets/165ad3ba-35e8-4e40-b157-6f4b2fd304e4)
i followed the text guide

**Comment by naughty360** [comment]
and it was really hard to find the cad drawing software everything is downloaded except cad files. i went to "different products" option and obtained this software.

**Comment by DefinetlyNotAI** [comment]
Ahh, i should have put a warning - IF something unusual or you are not finding something, use the video guide - it is safer for these kinds of errors

**Comment by DefinetlyNotAI** [comment]
Did you have solidworks ever before?

**Comment by DefinetlyNotAI** [comment]
Here is its fix:

https://www.youtube.com/watch?v=NL0B8DYRCA0

**Comment by DefinetlyNotAI** [comment]
This is a known bug for solidowrks BOTH legit and non-legit files, It is due to Windows messing with solidworks due to a past incompatibility issue

**Comment by DefinetlyNotAI** [comment]
https://www.solidworks.com/sw/support/techkb3072630.htm

The bug is code: [KB3072630](https://support.microsoft.com/en-us/kb/3072630)

Its old and from 2015 - Apologize for any inconveniace

**Comment by DefinetlyNotAI** [comment]
(May you please drop a star?)

**Comment by naughty360** [comment]
> Here is its fix:
> 
> https://www.youtube.com/watch?v=NL0B8DYRCA0

did it but here's a new error even though i didn't open any files of solid works
![Screenshot (117)](https://github.com/user-attachments/assets/2606c7fd-6a19-4c73-9315-fc296f64b0b3)

**Comment by naughty360** [comment]
> https://www.solidworks.com/sw/support/techkb3072630.htm
> 
> The bug is code: [KB3072630](https://support.microsoft.com/en-us/kb/3072630)
> 
> Its old and from 2015 - Apologize for any inconveniace

i don't have this installed

**Comment by naughty360** [comment]
can i know to uninstall this cleanly so i can try again.

**Comment by DefinetlyNotAI** [comment]
Ofcourse, So:

OPTIONAL: Create a system restore point (incase things go wrong for any reason)
1) Install IoBit Uninstaller (It will remove hidden and registry traces of solidworks) You can find it [here](https://www.iobit.com/en/advanceduninstaller.php)
2) After you uninstalled solidworks via IoBit installer, uninstall iobit.
3) Go to your C:\ Drive and delete all files you copied using the guide, that may have been left over - Especially in the following areas: C:\Program Files, C:\
4) After you remove ALL files, and checked in these 2 areas no solidwork related files exist, you can restart your computer

Afterwards everything should have been gone :)

**Comment by DefinetlyNotAI** [comment]
> > Here is its fix:
> > https://www.youtube.com/watch?v=NL0B8DYRCA0
> 
> did it but here's a new error even though i didn't open any files of solid works ![Screenshot (117)](https://private-user-images.githubusercontent.com/178680453/358920713-2606c7fd-6a19-4c73-9315-fc296f64b0b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMDMyNDcsIm5iZiI6MTcyNDAwMjk0NywicGF0aCI6Ii8xNzg2ODA0NTMvMzU4OTIwNzEzLTI2MDZjN2ZkLTZhMTktNGM3My05MzE1LWZjMjk2ZjY0YjBiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQxNzQyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDM1YzdjY2EyYzJmYTQ3OTFiZjY2ZWRlOGNmNDVmMDYzYzljYmFlN2YzMmM2NzQzYjEyYTViZWRlYTU5N2YwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AhY5uDF4EDKRslJflNqsupS15Iha1eNPfBnDNqUOprE)

Regarding this, you must restart your computer after significant changes, but its safer to do what the above re-installation guide was given to you, also to stay in the safe side, IT IS ADVISED TO RESTART AFTER INSTALLATION

**Comment by naughty360** [comment]
yeah the issue still remains the same even after that

**Comment by DefinetlyNotAI** [comment]
> yeah the issue still remains the same even after that

In that case follow my uninstallation guide

**Comment by DefinetlyNotAI** [comment]
> Ofcourse, So:
> 
> OPTIONAL: Create a system restore point (incase things go wrong for any reason)
> 
> 1. Install IoBit Uninstaller (It will remove hidden and registry traces of solidworks) You can find it [here](https://www.iobit.com/en/advanceduninstaller.php)
> 2. After you uninstalled solidworks via IoBit installer, uninstall iobit.
> 3. Go to your C:\ Drive and delete all files you copied using the guide, that may have been left over - Especially in the following areas: C:\Program Files, C:\
> 4. After you remove ALL files, and checked in these 2 areas no solidwork related files exist, you can restart your computer
> 
> Afterwards everything should have been gone :)

Here

**Comment by DefinetlyNotAI** [comment]
I will consider this as a closed question, feel free to ask me to reopen this, thank you.

**Comment by DefinetlyNotAI** [comment]
Hello, from one pirate to another, I must ask,
Do you still have the ZIP file from the guide link? It seems `GetIntoPC` is down, and many other people can't use Solidworks Cracked

If you do, sacrifice some of your time and upload it to google drive, and allow me to download it, so I may host it locally HERE!

---

Thank you 🫡
