### ISSUE TITLE
Getting Error (-8,554,0) in 2024

### ISSUE THREAD

**Issue by Archiel96** [DefinetlyNotAI/Solidworks-Crack#4]
Hi, I am trying to copy and then paste the files from Crack/SOLIDWORKS Corp/SOLIDWORKS to C:/Program Files/SOLIDWORKS Corp/SOLIDWORKS, but (-8,554,0) persists. 

I guess the files in Crack/SOLIDWORKS Corp/SOLIDWORKS doesn't have enough or the right files. Can you please check the folder structure and files.
![IMG_20240822_141837076](https://github.com/user-attachments/assets/9f21ce77-d262-421a-becc-e2df1316edfc)
![IMG_20240822_141935364](https://github.com/user-attachments/assets/efe18290-8912-4a05-95e3-22eab6627abf)

**Comment by DefinetlyNotAI** [comment]
Have you tried https://www.youtube.com/watch?v=NL0B8DYRCA0 ?

**Comment by DefinetlyNotAI** [comment]
Also have you made sure that you were fully disconnected from the internet while doing this? If not it will communicate with the server and crash the program, After it works for the first time, you may open the wifi

**Comment by DefinetlyNotAI** [comment]
This is a even better video fix, https://www.youtube.com/watch?v=mHcwJbmY2yY

I keep getting these errors with many people, so it might be a issue with a specific group of people, etc

**Comment by Archiel96** [comment]
> Also have you made sure that you were fully disconnected from the internet while doing this? If not it will communicate with the server and crash the program, After it works for the first time, you may open the wifi

Internet was disconnected while the software installed completely. Internet is yet not connected to system. :)

**Comment by DefinetlyNotAI** [comment]
Hmm, tried the video fixes?

**Comment by Archiel96** [comment]
> This is a even better video fix, https://www.youtube.com/watch?v=mHcwJbmY2yY
> 
> I keep getting these errors with many people, so it might be a issue with a specific group of people, etc

As we can see in the attached photo, there are only 3 files in SOLIDWORKS Corp/SOLIDWORKS folder. But in the video (though 2021 version) they have a lot more files. Already tried pasting these 3 files in C:/ drive.

**Comment by Archiel96** [comment]
> This is a even better video fix, https://www.youtube.com/watch?v=mHcwJbmY2yY
> 
> I keep getting these errors with many people, so it might be a issue with a specific group of people, etc

Already done this with the 3 files that are there in the attached photo. These might be something that we are missing.

**Comment by DefinetlyNotAI** [comment]
Wait, Thanks for reminding me, For some reason the Solidworks 2024 has this issue in the GetIntoPC

I advice installing 2021, its not so different than today, and is operational, Please note the cracked file are not my property so i cant get into detail

**Comment by DefinetlyNotAI** [comment]
I will check the website

**Comment by DefinetlyNotAI** [comment]
Yes, my device has the 2021 version, it works wonderfully

**Comment by DefinetlyNotAI** [comment]
shall i close the issue?

**Comment by Archiel96** [comment]
> shall i close the issue?

Sure! Thanks.

**Comment by DefinetlyNotAI** [comment]
Mind after it works dropping a star? Would appreciate it alot

**Comment by DefinetlyNotAI** [comment]
@Archiel96 Thanks for the star,

**Comment by DefinetlyNotAI** [comment]
Hello, from one pirate to another, I must ask,
Do you still have the ZIP file from the guide link? It seems `GetIntoPC` is down, and many other people can't use Solidworks Cracked

If you do, sacrifice some of your time and upload it to google drive, and allow me to download it, so I may host it locally HERE!

---

Thank you 🫡
