### ISSUE TITLE
Windows installer (w11pro) does not install Solidworks 2024

### ISSUE THREAD

**Issue by Michel-32** [DefinetlyNotAI/Solidworks-Crack#5]
Hye,
Downloaded Solidworks 2024 SP1 from here (zip format) ; extracted a s a .iso file.
All stesp went fine as per tuto.
But when starting application, windows installer starts configuration and a time after expiration date warnings, asks for installation drive (CD, USB...) as a .msi file.
Obviously, does not recognize the iso file...
TRied few options, but no success at this stage.
Help appreciated

**Comment by DefinetlyNotAI** [comment]
Alright, to help you i would appreciate any images or error codes,

Thanks

**Comment by Michel-32** [comment]
will do it
Thanks

**Comment by Michel-32** [comment]
Here is a short video (sorry it is in French...)
https://github.com/user-attachments/assets/59305be1-1027-4bfa-b368-eecc236d918f

**Comment by DefinetlyNotAI** [comment]
Hi, may i ask, did you fully merge ALL the registry?

**Comment by Michel-32** [comment]
Hye,
fully, I am not sure what you mean... I did as per readme.txt file, yes.
the two files .reg and the folder Solidworks Corp.
Did I forget anything ?

**Comment by DefinetlyNotAI** [comment]
Which tutorial did you use,

The error you experiance is pretty unique and new

If possible try using the video tutorial

Just download the mp4 file and follow its steps

**Comment by Michel-32** [comment]
The tuto readme.text attached in the donwloaded from Github.
I will Watch the vidéo 
Thanks for helping.

**Comment by DefinetlyNotAI** [comment]
NP, may you drop a star

**Comment by Michel-32** [comment]
Watched video
Nothing different from what I made...
So, I will remove this installation and start all over again.
Thanks

**Comment by DefinetlyNotAI** [comment]
Sorry for any inconveniance,

Just fyi I am not the person who actually made the cracked software

this is just the tutorial

**Comment by DefinetlyNotAI** [comment]
I will close this issue, please comment on this if anything else occurs :)

**Comment by DefinetlyNotAI** [comment]
Hello, from one pirate to another, I must ask,
Do you still have the ZIP file from the guide link? It seems `GetIntoPC` is down, and many other people can't use Solidworks Cracked

If you do, sacrifice some of your time and upload it to google drive, and allow me to download it, so I may host it locally HERE!

---

Thank you 🫡
