### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jy157** [DefinetlyNotAI/Solidworks-Crack#7]
Hi
After I have installed the 2024 software and tried to open the app, an error appeared saying that the software version is newer than the license key? i guess,? So I cant use it after all. I would like to use the 2024 version. Sorry for not providing the captured screen to you, I've uninstalled it... 
Please give me some advise

**Comment by DefinetlyNotAI** [comment]
Hi, Can you try the version 2021? Its the most stable and is documented from the video

Download the vid and follow its instructions

**Comment by jy157** [comment]
oh ok ill do that for now

**Comment by jy157** [comment]
oh ok ill do it now

**Comment by DefinetlyNotAI** [comment]
great,

**Comment by DefinetlyNotAI** [comment]
@jy157 Thank you for the star ⭐

**Comment by jy157** [comment]
could you provide the licence codes for 2024 because most of my work is done in 2024 and I can't open them

**Comment by jy157** [comment]
can you help me asap? I really need it rn

**Comment by DefinetlyNotAI** [comment]
The serial codes are super dynamic and change based on your hardware - This is the reason why cracking it is super hard,

If you need the 2024 version - Attempt reinstalling using the same steps as the video

I hope it fixes the issue for you.

**Comment by DefinetlyNotAI** [comment]
No, The serials are autogenerating using a crack-gen software that predicts the serial for your device, using a serial that was used by someone else will most likely just fail

Please install Solidworks 2024 again using the video tutorial

**Comment by jy157** [comment]
But all of the boxes for the serial numbers are blank. However, the video already has the codes typed in. That was all from the video tutorial. What should I do?

**Comment by DefinetlyNotAI** [comment]
Did you uninstall your corrupted copy - then reinstalled?

**Comment by DefinetlyNotAI** [comment]
Its very weird that this occured to you?

**Comment by jy157** [comment]
there was no need to uninstall stuff because this also happened on my first trial as well

**Comment by jy157** [comment]
there was no need to uninstall stuff because this also happened on my first trial as well

**Comment by DefinetlyNotAI** [comment]
attempt re-installation and update me

**Comment by jy157** [comment]
Ok

**Comment by jy157** [comment]
I got this error now![20240915_235211.jpg](https://github.com/user-attachments/assets/5691b72d-6300-4853-9806-2e6c446636d7)

**Comment by DefinetlyNotAI** [comment]
You have not fully uninstalled all files properlly, solidowrks is a program that deeply roots itself, so you must follow this guide to uninstall and reinstall - the error is due to residual files

OPTIONAL: Create a system restore point (incase things go wrong for any reason)

Install IoBit Uninstaller (It will remove hidden and registry traces of solidworks) You can find it [here](https://www.iobit.com/en/advanceduninstaller.php)
After you uninstalled solidworks via IoBit installer, uninstall iobit.
Go to your C:\ Drive and delete all files you copied using the guide, that may have been left over - Especially in the following areas: C:\Program Files, C:\
After you remove ALL files, and checked in these 2 areas no solidwork related files exist, you can restart your computer
Afterwards everything should have been gone :)


As a last resort if you can use solidworks 2021

**Comment by DefinetlyNotAI** [comment]
Sorry for any inconvenience - really

**Comment by jy157** [comment]
I followed all the procedures you guided including uninstalling residual files that were related to Solidworks, using the uninstaller you suggested but sadly this error message appeared. 

I **desperately need the 2024 version** as the 2021 version cannot open the files I created before.
Can you please help me with this issue?
Then it will be very very appreciated.
Thanks

![20240916_215339](https://github.com/user-attachments/assets/ad56c7ce-d07c-4c58-a4e9-55684a096ce3)

**Comment by DefinetlyNotAI** [comment]
This is now a new problem...
#3 and #4 
Its related to Windows.. nthn I can do about it - I am super sorry

**Comment by DefinetlyNotAI** [comment]
https://github.com/DefinetlyNotAI/Solidworks-Crack?tab=readme-ov-file#common-issues

**Comment by DefinetlyNotAI** [comment]
Hello, from one pirate to another, I must ask,
Do you still have the ZIP file from the guide link? It seems `GetIntoPC` is down, and many other people can't use Solidworks Cracked

If you do, sacrifice some of your time and upload it to google drive, and allow me to download it, so I may host it locally HERE!

---

Thank you 🫡
