### ISSUE TITLE
not pass license verification

### ISSUE THREAD

**Issue by dogukanaras** [DefinetlyNotAI/Solidworks-Crack#9]
When Solidworks Visualize 2024 is running, some features are disabled after a while. Ex: File Save

When I examine the log files, it says “Some features were turned off because they did not pass license verification”.

**Comment by DefinetlyNotAI** [comment]
Hello, from one pirate to another, I must ask,
Do you still have the ZIP file from the guide link? It seems `GetIntoPC` is down, and many other people can't use Solidworks Cracked

If you do, sacrifice some of your time and upload it to google drive, and allow me to download it, so I may host it locally HERE!

---

Thank you 🫡
